### ISSUE TITLE
Templates/Themes Support

### ISSUE THREAD

**Issue by onfire4g05** [greyshirtguy/ProPresenter7-Proto#1]
Is there a way to make this work with themes files? I actually may just be missing something and doing something wrong since I'm honestly not at all familiar with proto files. It seems like they're not getting the names of the identifiers and instead using numbers/ids for them when I export using `rv.data.Template`.

My use case for this is to push out "standard" themes to other campuses in our network. ProPresenter seems to hard link full file paths sometimes, and this causes issues on other devices that have different file paths; meanwhile they do have a way to relative link files, and I'm hoping to try to change to use that before I add the themes to our distro point. Right now, I have a work around for this, but I'd rather just "patch" the themes files... of course, provided Pro7 sees them correctly on the other side.

Command:
```
protoc --decode rv.data.Template ./propresenter.proto < ../Theme
```

Returns the following (trimmed the output):
```
1 {
  1: 1
  2 {
    1: 10
    2: 15
    3: 6
  }
  3: 1
  4 {
    1: 7
    2: 2
    3: 1
    4 {
      6: 0x3134383137353731
    }
  }
}
3 {
  1 {
    1 {
      1 {
        1 {
          1: "F385C1DC-C927-4DD8-892B-23CB1848CD0B"
        }
        2: "TextElement"
```

My specific problem, their stock theme has this:
```
            2 {
              1: "file:///Users/keahi/Documents/ProPresenter/Themes/Stock/White/Assets/EventPhoto.jpg"
              3: 1
              4 {
                1: 12
                2: "Assets/EventPhoto.jpg"
              }
            }
```

Unfortunately, my theme doesn't have that 4 block which I'm guessing is telling it it's built into the theme. I've tried various ways to get this to work, and it could be that I'm doing something wrong or a Pro bug.
```
            2 {
              1: "file:///Users/josborne/Documents/ProPresenter/Themes/Central/Notes/Lower%20Thirds/Assets/photo.png"
              3: 1
            }
```

**Comment by greyshirtguy** [comment]
It seems Template files don't contain an rv.data.Template message.
From what I can tell, they contain an rv.data.Template.Document message.

Change your decode command to:
protoc --decode **rv.data.Template.Document ./template.proto** < ../Theme

**Comment by greyshirtguy** [comment]
At a glance, that looks like the stock theme is including the RelativeFilePath field of the URL that points to the media.
4 = rv.data.URL.LocalRelativePath
1 is the root of the relative path with a value of 12 (which is ROOT_CURRENT_RESOURCE)
2 is the string path.

**Comment by greyshirtguy** [comment]
What you are doing sounds cool - I would love to check it out one day!
My plan to is fully automate the Pro7 setup for Sundays... Ideally to the point that **everything** (verses, photos, name slides, pre-service loop imags/videos, songs) is auto-magically ready when you walk in....all based off polling the PCO plan.

**Comment by onfire4g05** [comment]
Ah, this looks like it'll be perfect! Thank you and thank you for the work you've put into this! I might need to research how protocol buffers works more someday. Anyway, here's how the built in Pro7 template file is:

```
            url {
              absolute_string: "file:///Users/keahi/Documents/ProPresenter/Themes/Stock/White/Assets/EventPhoto.jpg"
              platform: PLATFORM_MACOS
              local {
                root: ROOT_CURRENT_RESOURCE
                path: "Assets/EventPhoto.jpg"
              }
            }
```

This will be perfect, since that's where I'm trying to store the resources anyway. There may be an option I'm missing in Pro7 somewhere that'll move them to the resource folder and all, but I haven't been able to find it (I thought "Manage Media Automatically" may do it, but it didn't seem to... could also be a bug). Either way, before I push the documents to other campuses, I prefer to verify things are correct before, and this will sanely allow that.

As far as what I'm doing... we're just starting our roll out of Pro7 to our campuses (we have ~20). So far things have been fairly smooth. While campuses can do things on their own, we like to keep a few things standard (like lyric styles, name slates, etc). While the Pro7 "Sync" functionality would work to some extent, it loses some of the control we'd like to have. For example, we want campuses to have their own Themes, but our main repository we want to be easy to update to everyone + be read-only. We also want campuses to be able to make documents, but the main lyric library should be the same between them all. So we're using separate libraries and doing different things in our update script. The update script is pretty simple, honestly. It copies from our Dropbox to a local folder, and then copies over files in Pro7.

Our automation may be a bit different in what you're looking to automate. What you're looking at sounds very exciting. :) I'd love to get to a point like that, but with having so many campuses, for us anyway, it gets to a point where we have to balance that with "over-automation". We don't want people to get so comfortable they don't know how to do the basics when something out of the ordinary happens, or it fail completely haha. That doesn't mean we won't get there eventually, though with time, training, etc.
