### ISSUE TITLE
Missing entries in GraphicsData.proto

### ISSUE THREAD

**Issue by simube** [greyshirtguy/ProPresenter7-Proto#2]
Hi

It seems that ProPresenter had new features added for "LineFillMask"

When I parse a .pro-file I get some unassigned entries here:
Graphics\Text\LineFillMask

They look like:
4: 0
5: some binary value
6: some binary value

In ProPresenter there are new options for the line fill background width (longest line, line length) and some more offsets.

Is there a way to reverse-engineer these?

Simon

**Comment by greyshirtguy** [comment]
Thanks for letting me know. I just updated some files in a new commit that hopefully solves your issue!

**Comment by simube** [comment]
Wow, thanks!

Yes, it seems that you added the lines missing.
Thanks for your great work!
Simon
