### ISSUE TITLE
PlaylistDocument: Failed to parse input

### ISSUE THREAD

**Issue by vjccruz** [greyshirtguy/ProPresenter7-Proto#3]
Hi,

I'm using ProPresenter v7.9.1 and protoc (libprotoc 3.21.0).

When I try decode a playlist, I get a "failed to parse input" error message:
![image](https://user-images.githubusercontent.com/5125346/170669014-fdd55315-eba8-4233-9b74-e743beb20414.png)

Exists any method for debug to help you?

Best regards,
Vasco Cruz

**Comment by greyshirtguy** [comment]
G'day mate.
You are making a bit of  mistake there - trying to decode an exported playlist as a Goodle Protocol Buffer - It's not!

FYI: exported playlists are ZIP files that contain multiple files/folders.  Within  that zip is a playlist file ("data") - you can decode that!
