### ISSUE TITLE
Support for 7.10.*

### ISSUE THREAD

**Issue by maxned** [greyshirtguy/ProPresenter7-Proto#5]
I have not checked but I presume that the protos should be regenerated for the latest PP version, 7.10.4 at the time of this writing.

Furthermore, perhaps you could share the exact scripts that you use to generate these?

**Comment by greyshirtguy** [comment]
I have not updated.  I will soon!

I'm not sure I should share actual code I used (It's against T&C to reverse engineer - so I am not sure if I am pushing my luck even sharing this much!)

I mention (at a high level) how I approached it here: 
https://greyshirtguy.com/blog/pro7fileformat1/
https://greyshirtguy.com/blog/propresenter-7-file-format-part-2/

**Comment by maxned** [comment]
Thank you!

Ah I see. But I am honestly very grateful for your work. I've been wanting to create a single source of truth database of text files for all lyrics at my church that could also be used in other ways and one of the things holding me back was working with the presentation files. The API they provide isn't powerful enough yet and this provides the most flexibility.

**Comment by arlinsandbulte** [comment]
Hi Dan, my Pro7 Media Sweeper app might need updated proto files for 7.10.
7.10 added support for Playlist Templates, and one user has reported parse errors on the file: "\ProPresenter\Playlists\Templates\PlaylistTemplates"
See issue here: https://github.com/arlinsandbulte/Pro7-Media-Sweeper/issues/12

**Comment by maxned** [comment]
I actually recently found this new library that someone wrote to parse out proto files from executables. https://github.com/arkadiyt/protodump

I used it on the Pro7 files and it seems to have output valid files!

Here's the command I wrote: `find /Applications/ProPresenter.app/ -type f -perm +111 -print -exec ./protodump -file {} -output ../Pro7-protos \;`

You need to be in the folder with the `protodump` executable and you need to have a folder called `Pro7-protos` just outside it.

**Comment by greyshirtguy** [comment]
@arlinsandbulte yep, Ill refresh protos soon..

@maxned That protodump is very interesting.... I used different maual methods to get protos From the windows verion 
I'll def have to check it out!

**Comment by greyshirtguy** [comment]
Updated using current 7.11 beta (so it should cover all 7.10.* and earlier)

**Comment by greyshirtguy** [comment]
Ohh, that protodump is slightly more _complete_ than my methods as it includes some option declaration that I missed...
I might move to using that tool instead for keeping this repo updated....(esp since my method is several manual steps v's this scriptable command!!)

Thanks for pointing it out @maxned !

**Comment by maxned** [comment]
Wonderful! Thanks for doing this to begin with!

**Comment by greyshirtguy** [comment]
I'd love to see what you build! I also have some dreams about introducing integrations and automations that can work with Pro7 files at my Church....

For now, I keep getting distracted by other ideas... like a [ChordEditor](https://github.com/greyshirtguy/Pro7ChordEditorWin)

**Comment by arlinsandbulte** [comment]
Just poking around a bit.
I did not find a mention of a Playlist Template.  This was introduced in 7.10.
Should I?

**Comment by greyshirtguy** [comment]
I must confess I did not check myself - just did the extract from 7.11 and assumed playlist template would be covered... let me take a peek!

**Comment by greyshirtguy** [comment]
Okay, found my booboo and added missing "playlistTemplate.proto" to support rv.data.PlaylistTemplate

**Comment by greyshirtguy** [comment]
....Interestingly `protodump` missed it too!

**Comment by ioanlucut** [comment]
Hey @greyshirtguy.
Thanks a lot for your repo & work.

Can I ask if you know how I can debug further how to add a media action to a cue/slide? Can we chat anywhere?

Thanks a lot.
