### ISSUE TITLE
Updating propresenter presentation

### ISSUE THREAD

**Issue by tuxtlequino** [greyshirtguy/ProPresenter7-Proto#6]
I followed your tutorial and I was able to decode a presentation with the following.

`protoc --decode rv.data.Presentation ./presentation.proto < /Users/user/Documents/ProPresenter/Libraries/Default/test.pro > simplePresentation.txt`

Now, I am assuming that after reading that text, I could do the opposite and recode the resulting file back into a ProPresenter file like this,

`cat SimplePresentation.txt | protoc  --encode rv.data.Presentation ./presentation.proto  > test.pro`

But the resulting file does not have the slides that the original propresenter file had. Just to make sure that I wasn't missing something, I decided to do the following.

`protoc --decode rv.data.Presentation ./presentation.proto < ./test.pro > simplePresentation2.txt`

And then check if there was a difference between the original file and the one decoded from the encoding

`diff simplePresentation.txt simplePresentation2.txt`

And they were the same. I think that the data structure in the protobuf from 7.11 to 7.12 may have broken something, but I am just guessing. 

I am using Ventura and Propresenter 7.12 if that helps.

**Comment by wegylexy** [comment]
I wonder if the author has some tools to generate `.proto` files by extracting classes from the Visual Studio solution generated by `ILSpy` decompilation of `Pro.SerializationInterop.dll`.

**Comment by tuxtlequino** [comment]
He mentioned using DLLs but never got more into it. I am not familiar with Windows and .NET programming, but if someone could update this, that would be great. The idea of creating a presentation using something like Golang sounds amazing but unobtainable for now!

**Comment by wegylexy** [comment]
I tried to reverse engineered 7.15.0.18 here https://github.com/wegylexy/ProPresenter7-Proto/tree/v7.15 but haven't tested it yet.

`Pro.SerializationInterop.dll` per se does not depend on WPF and should work on Linux and Mac too. I'm using .NET 8 to load it.

**Comment by tuxtlequino** [comment]
Thank you very much. I will give it a try on Monday and see if I can get it to work. Sadly I have never done any work with .NET and how it seems that you can analyze structures using reflection.  Anyway. I really appreciate this. Thanks!

**Comment by greyshirtguy** [comment]
@wegylexy  Nice reverse engineering code!
At a glance, yours looks a bit more clever than mine (which I have not shared).

I've been very busy over last year - but will have free time after April to get back into other things (like this).

In the meantime, I will update the protos for 7.16

**Comment by wegylexy** [comment]
Didn't notice. Now we have 7.16.1.2 https://github.com/wegylexy/ProPresenter7-Proto/tree/v7.16

**Comment by tuxtlequino** [comment]
Hey Wegylexy, for some reason your proto files do not work for me. But the new ones from greyshirt do. Thank you very much both of you. It seems that the resulting JSON is way to complicated to just create a simple presentation. I may get to it next month and see if I can do so anyway.

**Comment by wegylexy** [comment]
@tuxtlequino GPT generated bad code 😅 fixed in https://github.com/wegylexy/ProPresenter7-Proto/commit/110e28d926a126d2cadb5c566784cc3914cc3608

**Comment by stevegore** [comment]
In case anyone else finds this, you can also just extract these on a Mac using `protodump`:

```bash
go install github.com/arkadiyt/protodump/cmd/protodump@latest
find /Applications/ProPresenter.app/ -type f -perm +111 -print -exec protodump -file {} -output ./proto \;
```

**Comment by greyshirtguy** [comment]
Thanks for reminder on that one. I starred that ages ago and forgot all about it! And it's a much easier option!
